# -*- coding: utf-8 -*-
"""
Created on Wed Jun  4 09:32:22 2025

@author: ACRANMER
"""
import streamlit as st
import pandas as pd
import json

# Function for loading data
@st.cache_data
def load_data(start_year):
    use_columns = ['Municipality','Year',
                   # overview data
                   'HH with HPs','HH with PVs','Percent Res EVs','Percent EVs', 
                   'Residential Electricity per HH', 'Residential Gas per HH',
                   'Residential Energy per HH',
                   'Total (MTCO2e)','Per Capita (MTCO2e)',
                   'Total Residential (MTCO2e)','Per Capita Residential (MTCO2e)',
                   'Per Household Residential (MTCO2e)',
                   'Total Commercial & Industrial (MTCO2e)',
                   'Total Electricity (MTCO2e)','Total Gas (MTCO2e)',
                   'Total Propane (MTCO2e)','Total Fuel Oil (MTCO2e)',
                   'Total Gasoline (MTCO2e)','Total Diesel (MTCO2e)',
                   'Total Solid Waste Emissions (MTCO2e)','Total Wastewater Emissions (MTCO2e)',
                   'Total Residential Buildings (MTCO2e)','Total Commercial & Industrial Buildings (MTCO2e)',
                   'Total Transportation (MTCO2e)',#'Public Transit Total (MTCO2e)',
                   'Total Waste (MTCO2e)',
                   'Total Electricity (MMBTU)','Total Gas (MMBTU)',
                   'Total Propane (MMBTU)','Total Fuel Oil (MMBTU)',
                   'Total Gasoline (MMBTU)','Total Diesel (MMBTU)',
                   'Total Residential Buildings (MMBTU)',
                   'Total Commercial & Industrial Buildings (MMBTU)',
                   'Total Transportation (MMBTU)',
                   # demographic data
                   'Population','Households','Total Heating Fuel Households',
                   'Median household income','Median age (years)',
                   'pct owner occupied','pct renter occupied', 'pct single family', 'pct ng', 'pct elec',
                   'pct fuel oil', 'pct propane', 'pct wood', 'pct short commute',
                   'pct work from home', 'pct public transit', 'pct black', 'pct latinx',
                   'pct asian', 'pct white', 'pct BS+', 'pct Limited English',
                   'pct households <$50k', 'pct households $50-100k',
                   'Percent of EJ block groups',
                   'Electricity','Utility gas','Fuel oil, kerosene, etc.','Bottled or tank gas',
                   'Wood','Solar energy','Coal or coke','Other fuel','No fuel used',
                   # buildings data
                   'CEA Y/N','Average annual location participation rate [%]',
                   'Cumulative location participation rate [%] (4)',
                   'Commercial & Industrial IOU Electricity (MWh)',
                   'Commercial & Industrial IOU Gas (therms)',
                   'Residential IOU Electricity (MWh)', 'Residential IOU Gas (therms)',
                   'Total IOU Electricity (MWh)', 'Total IOU Gas (therms)',
                   'Municipal (Mass Save)', 'No Gas (Mass Save)',
                   'Jan Commercial & Industrial IOU Electricity (MWh)','Jan Commercial & Industrial IOU Gas (therms)',
                   'Jan Residential IOU Electricity (MWh)','Jan Residential IOU Gas (therms)', 
                   'Jan Total IOU Electricity (MWh)','Jan Total IOU Gas (therms)',
                   'Feb Commercial & Industrial IOU Electricity (MWh)','Feb Commercial & Industrial IOU Gas (therms)',
                   'Feb Residential IOU Electricity (MWh)','Feb Residential IOU Gas (therms)', 
                   'Feb Total IOU Electricity (MWh)','Feb Total IOU Gas (therms)',
                   'Mar Commercial & Industrial IOU Electricity (MWh)','Mar Commercial & Industrial IOU Gas (therms)',
                   'Mar Residential IOU Electricity (MWh)','Mar Residential IOU Gas (therms)', 
                   'Mar Total IOU Electricity (MWh)','Mar Total IOU Gas (therms)',
                   'Apr Commercial & Industrial IOU Electricity (MWh)','Apr Commercial & Industrial IOU Gas (therms)',
                   'Apr Residential IOU Electricity (MWh)','Apr Residential IOU Gas (therms)', 
                   'Apr Total IOU Electricity (MWh)','Apr Total IOU Gas (therms)',
                   'May Commercial & Industrial IOU Electricity (MWh)','May Commercial & Industrial IOU Gas (therms)',
                   'May Residential IOU Electricity (MWh)','May Residential IOU Gas (therms)', 
                   'May Total IOU Electricity (MWh)','May Total IOU Gas (therms)',
                   'Jun Commercial & Industrial IOU Electricity (MWh)','Jun Commercial & Industrial IOU Gas (therms)',
                   'Jun Residential IOU Electricity (MWh)','Jun Residential IOU Gas (therms)',
                   'Jun Total IOU Electricity (MWh)','Jun Total IOU Gas (therms)',
                   'Jul Commercial & Industrial IOU Electricity (MWh)','Jul Commercial & Industrial IOU Gas (therms)',
                   'Jul Residential IOU Electricity (MWh)','Jul Residential IOU Gas (therms)', 
                   'Jul Total IOU Electricity (MWh)','Jul Total IOU Gas (therms)',
                   'Aug Commercial & Industrial IOU Electricity (MWh)','Aug Commercial & Industrial IOU Gas (therms)',
                   'Aug Residential IOU Electricity (MWh)','Aug Residential IOU Gas (therms)', 
                   'Aug Total IOU Electricity (MWh)','Aug Total IOU Gas (therms)',
                   'Sept Commercial & Industrial IOU Electricity (MWh)','Sept Commercial & Industrial IOU Gas (therms)',
                   'Sept Residential IOU Electricity (MWh)','Sept Residential IOU Gas (therms)', 
                   'Sept Total IOU Electricity (MWh)','Sept Total IOU Gas (therms)',
                   'Oct Commercial & Industrial IOU Electricity (MWh)','Oct Commercial & Industrial IOU Gas (therms)',
                   'Oct Residential IOU Electricity (MWh)','Oct Residential IOU Gas (therms)', 
                   'Oct Total IOU Electricity (MWh)','Oct Total IOU Gas (therms)',
                   'Nov Commercial & Industrial IOU Electricity (MWh)','Nov Commercial & Industrial IOU Gas (therms)',
                   'Nov Residential IOU Electricity (MWh)','Nov Residential IOU Gas (therms)', 
                   'Nov Total IOU Electricity (MWh)','Nov Total IOU Gas (therms)',
                   'Dec Commercial & Industrial IOU Electricity (MWh)','Dec Commercial & Industrial IOU Gas (therms)',
                   'Dec Residential IOU Electricity (MWh)','Dec Residential IOU Gas (therms)', 
                   'Dec Total IOU Electricity (MWh)','Dec Total IOU Gas (therms)', 
                   'Residential MLP Electricity (MWh)', 'Commercial MLP Electricity (MWh)',
                   'Industrial MLP Electricity (MWh)',
                   'Commercial & Industrial MLP Electricity (MWh)',
                   'Municipal MLP Electricity (MWh)', 'Total MLP Electricity (MWh)',
                   'Residential MLP Gas (therms)', 'Commercial MLP Gas (therms)',
                   'Industrial MLP Gas (therms)',
                   'Commercial & Industrial MLP Gas (therms)',
                   'Municipal MLP Gas (therms)', 'Total MLP Gas (therms)',
                   'Residential Electricity (MWh)',
                   'Commercial & Industrial Electricity (MWh)', 'Total Electricity (MWh)',
                   'Residential Gas (therms)', 'Commercial & Industrial Gas (therms)',
                   'Total Gas (therms)',
                    'Residential Electricity (MMBTU)','Residential Gas (MMBTU)',
                    'Commercial & Industrial Electricity (MMBTU)','Commercial & Industrial Gas (MMBTU)',
                    'Residential Electricity (MTCO2e)','Commercial & Industrial Electricity (MTCO2e)',
                    'Total Electricity (MTCO2e)', 'Residential Gas (MTCO2e)',
                    'Commercial & Industrial Gas (MTCO2e)', 'Total Gas (MTCO2e)',
                    'Residential Fuel Oil (gallons)','Residential Propane (gallons)', 
                    'Residential Propane (MMBTU)','Residential Fuel Oil (MMBTU)', 
                    'Commercial Fuel Oil (gallons)','Commercial Fuel Oil (MMBTU)', 'Total Fuel Oil (MMBTU)',
                    'Residential Fuel Oil (MTCO2e)','Commercial Fuel Oil (MTCO2e)','Total Fuel Oil (MTCO2e)',
                    'Total Propane (MMBTU)', 'Residential Propane (MTCO2e)', 'Total Propane (MTCO2e)',
                    'Heat pumps all (accounts)', 'Heat pumps hvac (accounts)', 
                    'Cumulative heat pumps all (accounts)','Cumulative heat pumps hvac (accounts)',
                    # add solar data here once cleaned set is added in
                    'Capacity (kW DC) All',
                    'Capacity (kW DC) Residential',
                    'Capacity (kW DC) Commercial',
                    'Cumulative Capacity (kW DC) All',
                    'Cumulative Capacity (kW DC) Residential',
                    'Cumulative Capacity (kW DC) Multi-family residential',
                    'Cumulative Capacity (kW DC) Mixed Use',
                    'Cumulative Capacity (kW DC) Commercial',
                    'Cumulative Capacity (kW DC) Municipal',
                    'Cumulative Capacity (kW DC) Industrial',
                    'Cumulative Capacity (kW DC) Agricultural',
                    'Cumulative Capacity (kW DC) Community Solar',
                    'Cumulative Capacity (kW DC) Other',
                    'Cumulative Capacity (kW DC) Unknown',
                    'Cumulative Project Count Residential',
                    'Cumulative Project Count Multi-family residential',
                    'Cumulative Project Count Mixed Use',
                    'Cumulative Project Count Commercial',
                    'Cumulative Project Count Municipal',
                    'Cumulative Project Count Industrial',
                    'Cumulative Project Count Agricultural',
                    'Cumulative Project Count Community Solar',
                    'Cumulative Project Count Other',
                    'Cumulative Project Count Unknown',
                    # transportation data
                    'Count FFs 01','Count FFs 07', 'Count GHYs 01', 'Count GHYs 07', 'Count PHEVs 01',
                    'Count PHEVs 07', 'Count BEVs 01', 'Count BEVs 07', 'Count FCEVs 01',
                    'Count FCEVs 07', 'Count Total Vehicles 01', 'Count Total Vehicles 07',
                    'Total Residential Vehicles 01', 'Total Residential Vehicles 07',
                    'Total Commercial Vehicles 01', 'Total Commercial Vehicles 07',
                    'Total Municipal Vehicles 01', 'Total Municipal Vehicles 07',
                    'Total State Vehicles 01','Total State Vehicles 07',
                    'Count 01 Electric Vehicle Commercial','Count 01 Electric Vehicle Municipal',
                    'Count 01 Electric Vehicle Passenger','Count 01 Electric Vehicle State', 
                    'Count 01 Fossil Fuel Commercial','Count 01 Fossil Fuel Municipal', 
                    'Count 01 Fossil Fuel Passenger','Count 01 Fossil Fuel State',
                    'Count 01 Fuel Cell Electric Vehicle Commercial','Count 01 Fuel Cell Electric Vehicle Municipal',
                    'Count 01 Fuel Cell Electric Vehicle Passenger','Count 01 Fuel Cell Electric Vehicle State',
                    'Count 01 Hybrid Electric Vehicle Commercial','Count 01 Hybrid Electric Vehicle Municipal',
                    'Count 01 Hybrid Electric Vehicle Passenger','Count 01 Hybrid Electric Vehicle State',
                    'Count 01 Plug-in Hybrid Electric Commercial','Count 01 Plug-in Hybrid Electric Municipal',
                    'Count 01 Plug-in Hybrid Electric Passenger','Count 01 Plug-in Hybrid Electric State',
                    'AnnualVMT Commercial Electric Vehicle','AnnualVMT Commercial Fossil Fuel',
                    'AnnualVMT Commercial Fuel Cell Electric Vehicle','AnnualVMT Commercial Hybrid Electric Vehicle',
                    'AnnualVMT Commercial Plug-in Hybrid Electric','AnnualVMT Municipal Electric Vehicle',
                    'AnnualVMT Municipal Fossil Fuel','AnnualVMT Municipal Fuel Cell Electric Vehicle',
                    'AnnualVMT Municipal Hybrid Electric Vehicle','AnnualVMT Municipal Plug-in Hybrid Electric',
                    'AnnualVMT Passenger Electric Vehicle','AnnualVMT Passenger Fossil Fuel',
                    'AnnualVMT Passenger Fuel Cell Electric Vehicle','AnnualVMT Passenger Hybrid Electric Vehicle',
                    'AnnualVMT Passenger Plug-in Hybrid Electric','AnnualVMT State Electric Vehicle', 'AnnualVMT State Fossil Fuel',
                    'AnnualVMT State Fuel Cell Electric Vehicle','AnnualVMT State Hybrid Electric Vehicle',
                    'AnnualVMT State Plug-in Hybrid Electric',
                    'Annual Gasoline (gallons) Commercial Fossil Fuel',
                    'Annual Gasoline (gallons) Commercial Hybrid Electric Vehicle','Annual Gasoline (gallons) Commercial Plug-in Hybrid Electric',
                    'Annual Gasoline (gallons) Municipal Fossil Fuel',
                    'Annual Gasoline (gallons) Municipal Hybrid Electric Vehicle','Annual Gasoline (gallons) Municipal Plug-in Hybrid Electric',
                    'Annual Gasoline (gallons) Passenger Fossil Fuel',
                    'Annual Gasoline (gallons) Passenger Hybrid Electric Vehicle','Annual Gasoline (gallons) Passenger Plug-in Hybrid Electric',
                    'Annual Gasoline (gallons) State Fossil Fuel',
                    'Annual Gasoline (gallons) State Hybrid Electric Vehicle','Annual Gasoline (gallons) State Plug-in Hybrid Electric',
                    'Annual Diesel (gallons) Commercial Fossil Fuel',
                    'Annual Diesel (gallons) Commercial Hybrid Electric Vehicle','Annual Diesel (gallons) Commercial Plug-in Hybrid Electric',
                    'Annual Diesel (gallons) Municipal Fossil Fuel',
                    'Annual Diesel (gallons) Municipal Hybrid Electric Vehicle','Annual Diesel (gallons) Municipal Plug-in Hybrid Electric',
                    'Annual Diesel (gallons) Passenger Fossil Fuel',
                    'Annual Diesel (gallons) Passenger Hybrid Electric Vehicle','Annual Diesel (gallons) Passenger Plug-in Hybrid Electric',
                    'Annual Diesel (gallons) State Fossil Fuel',
                    'Annual Diesel (gallons) State Hybrid Electric Vehicle','Annual Diesel (gallons) State Plug-in Hybrid Electric',
                    'Annual Vehicle Electricity (MWh) Commercial Electric Vehicle',
                    'Annual Vehicle Electricity (MWh) Commercial Plug-in Hybrid Electric',
                    'Annual Vehicle Electricity (MWh) Municipal Electric Vehicle',
                    'Annual Vehicle Electricity (MWh) Municipal Plug-in Hybrid Electric',
                    'Annual Vehicle Electricity (MWh) Passenger Electric Vehicle',
                    'Annual Vehicle Electricity (MWh) Passenger Plug-in Hybrid Electric',
                    'Annual Vehicle Electricity (MWh) State Electric Vehicle',
                    'Annual Vehicle Electricity (MWh) State Plug-in Hybrid Electric',
                    'Count 1 Year Commercial 01', 'Count 1 Year Commercial 07',
                    'Count 1 Year Municipal 01', 'Count 1 Year Municipal 07',
                    'Count 1 Year Passenger 01', 'Count 1 Year Passenger 07',
                    'Count 1 Year State 01', 'Count 1 Year State 07',
                    'Count 10 Years + Commercial 01', 'Count 10 Years + Commercial 07',
                    'Count 10 Years + Municipal 01', 'Count 10 Years + Municipal 07',
                    'Count 10 Years + Passenger 01', 'Count 10 Years + Passenger 07',
                    'Count 10 Years + State 01', 'Count 10 Years + State 07',
                    'Count 2-5 Years Commercial 01', 'Count 2-5 Years Commercial 07',
                    'Count 2-5 Years Municipal 01', 'Count 2-5 Years Municipal 07',
                    'Count 2-5 Years Passenger 01', 'Count 2-5 Years Passenger 07',
                    'Count 2-5 Years State 01', 'Count 2-5 Years State 07',
                    'Count 5-10 Years Commercial 01', 'Count 5-10 Years Commercial 07',
                    'Count 5-10 Years Municipal 01', 'Count 5-10 Years Municipal 07',
                    'Count 5-10 Years Passenger 01', 'Count 5-10 Years Passenger 07',
                    'Count 5-10 Years State 01', 'Count 5-10 Years State 07',
                    'Count New Commercial 01', 'Count New Commercial 07',
                    'Count New Municipal 01', 'Count New Municipal 07',
                    'Count New Passenger 01', 'Count New Passenger 07',
                    'Count New State 01', 'Count New State 07',
                    'Residential Gasoline (gallons)','Commercial Gasoline (gallons)', 
                    'Municipal Gasoline (gallons)','State Gasoline (gallons)', 
                    'Residential Diesel (gallons)','Commercial Diesel (gallons)', 
                    'Municipal Diesel (gallons)','State Diesel (gallons)', 
                    'Residential Vehicle Electricity (MWh)',
                    'Commercial Vehicle Electricity (MWh)',
                    'Municipal Vehicle Electricity (MWh)',
                    'State Vehicle Electricity (MWh)', 'Total Gasoline (gallons)',
                    'Total Diesel (gallons)', 'Total Vehicle Electricity (MWh)',
                    'Residential Gasoline (MMBTU)', 'Residential Diesel (MMBTU)',
                    'Residential Vehicle Electricity (MMBTU)',
                    'Commercial Gasoline (MMBTU)', 'Commercial Diesel (MMBTU)',
                    'Commercial Vehicle Electricity (MMBTU)', 'Municipal Gasoline (MMBTU)',
                    'Municipal Diesel (MMBTU)', 'Municipal Vehicle Electricity (MMBTU)',
                    'Total Gasoline (MMBTU)', 'Total Diesel (MMBTU)',
                    'Total Vehicle Electricity (MMBTU)', 'Count Res EVs 01',
                    'Percent Res New 01', 'Percent Res 10+ 01',
                    'New Level 1 Station Count', 'New Level 2 Station Count',
                    'New Level 3 Station Count', 'Total Level 1 Station Count',
                    'Total Level 2 Station Count', 'Total Level 3 Station Count',
                    'New Level All Station Count', 'Total Level All Station Count',
                    'Transit Biodiesel (gallons)', 'Transit CNG (gallon eq)',
                    'Transit Diesel (gallons)', 'Transit Electric Battery (kWh)',
                    'Transit Electricity (kWh)', 'Transit Gasoline (gallons)',
                    'MBTA Diesel (gallons)', 'MBTA Electricity (MWh)', 'MBTA CNG (mmbtu)',
                    'MBTA Diesel (MTCO2e)', 'MBTA Electricity (MTCO2e)',
                    'MBTA CNG (MTCO2e)',
                    'Total Public Transportation (MMBTU)','Total Public Transportation (MTCO2e)',
                    'Residential Gasoline (MTCO2e)','Residential Diesel (MTCO2e)','Residential Vehicle Electricity (MTCO2e)',
                    'Commercial Gasoline (MTCO2e)', 'Commercial Diesel (MTCO2e)','Commercial Vehicle Electricity (MTCO2e)', 
                    'State Gasoline (MTCO2e)','State Diesel (MTCO2e)', 'State Vehicle Electricity (MTCO2e)',
                    'Municipal Gasoline (MTCO2e)', 'Municipal Diesel (MTCO2e)','Municipal Vehicle Electricity (MTCO2e)', 
                    'Total Gasoline (MTCO2e)','Total Diesel (MTCO2e)','Total Vehicle Electricity (MTCO2e)',
                    # waste data
                    'Incinerator',
                    'Total Number of Households',
                    'Households Served by Municipal Trash Program','Households Served by Municipal Recycling Program', 
                    'trash','single stream recyc', 'other recyc', 'organics', 
                    'landfill','combustion', 'net exports',
                    'MWRA AD (MTCO2e)', 'WWTP (MTCO2e)', 'Septic (MTCO2e)', 'AD Community',
                    'Total Wastewater Emissions (MTCO2e)', 'Landfill (MTCO2e)',
                    'Incineration (MTCO2e)', 'Compost (MTCO2e)',
                   ]
    df = pd.read_csv('datasets/municipal_emissions.csv', usecols=use_columns, low_memory=False)
    gdf = json.load(open('datasets/municipalities.geojson'))
    #gdf = gdf.to_crs(4326)
    
    dataset_ma = pd.concat([df.loc[df['Municipality']=='Massachusetts',:],df.loc[df['Municipality']!='Massachusetts',:]],axis=0)
    dataset = dataset_ma[dataset_ma['Year']>=start_year]
    
    if 'df' not in st.session_state:
        st.session_state.df = dataset
    if 'gdf' not in st.session_state:
        st.session_state.gdf = gdf
    
    df_solar = pd.read_csv('datasets/solar_data_updated.csv')
    if 'df_solar' not in st.session_state:
        st.session_state.df_solar = df_solar
    
    return dataset,gdf,df_solar



